// Full UI localization. Every interface string lives here, keyed by a stable id and
// provided in all three languages. Data-driven content (sutra names, translations,
// glossary definitions) is NOT here — it comes from the synced bundle and already
// switches with the language toggle.
//
// Use via the `t` function from useLang(): t('nav.home'), t('shloka.verse', { n: 3 }).
// Placeholders look like {name}; pass them in the vars object.
// Prose strings may use **bold**, *italic*, and `code` — render them through <RichText>.

import type { Lang } from './types'

export type TFunc = (key: string, vars?: Record<string, string | number>) => string

type Dict = Record<string, string>

const english: Dict = {
  // nav / header
  'nav.home': 'Home',
  'nav.rites': 'Pratikramaṇas',
  'nav.glossary': 'Glossary',
  'nav.about': 'About',
  'brand.subtitle': 'Achhalgach · Vidhipakṣa',
  'search.button': 'Search',
  'search.aria': 'Open search',
  'toggle.lang': 'Choose language',
  'toggle.theme.toLight': 'Switch to light theme',
  'toggle.theme.toDark': 'Switch to dark theme',
  'toggle.menu': 'Toggle menu',

  // search dialog
  'search.placeholder': 'Search sūtras, verses, glossary…',
  'search.hint': 'Type to search across all sūtras, verses, and glossary terms.',
  'search.noMatch': 'No matches for “{q}”.',
  'search.type.sutra': 'Sūtra',
  'search.type.shloka': 'Verse',
  'search.type.glossary': 'Glossary',
  'search.type.vidhi': 'Vidhi',
  // common
  'common.copy': 'Copy',
  'common.copied': 'Copied',
  'common.copyTitle': 'Copy to clipboard',
  'common.save': 'Save',
  'common.saved': 'Saved',
  'common.print': 'Print',
  'common.loading': 'Loading…',
  'common.preparing': 'Preparing the corpus…',
  'common.link': 'Link',

  // breadcrumbs / common nouns
  'crumb.home': 'Home',
  'crumb.sutras': 'Sūtras',
  'crumb.pratikramans': 'Pratikramaṇas',
  'crumb.glossary': 'Glossary',
  'crumb.about': 'About',
  'crumb.designSystem': 'Design System',

  // states / errors
  'error.title': 'Something went wrong',
  'error.resync': 'If the translation pipeline is still running, re-run `npm run sync-data` and reload.',
  'notFound.eyebrow': 'Not found',
  'notFound.title': 'This page could not be found',
  'notFound.body':
    'The link may be mistyped, or the corresponding text has not yet been generated by the translation pipeline.',
  'notFound.home': 'Return home',
  'notFound.browse': 'Browse the Pratikramaṇas',

  // progress / in-progress
  'progress.textPending': 'Text pending',
  'progress.byLang': 'Translation progress by language',
  'progress.verseTextPending': 'The original verse text for this passage is pending extraction.',
  'progress.verseInProgress':
    'Translation & commentary for this verse are being prepared in the selected language. Try another language, or check back as the corpus grows.',

  // āvaśyaka
  'av.word': 'Āvaśyaka',
  'av.short': 'Āv {n}',
  'av.ordinal.1': '1st',
  'av.ordinal.2': '2nd',
  'av.ordinal.3': '3rd',
  'av.ordinal.4': '4th',
  'av.ordinal.5': '5th',
  'av.ordinal.6': '6th',

  // shloka layers
  'shloka.toRecite': 'To recite',
  'shloka.toReciteIast': 'To recite (IAST)',
  'shloka.plainMeaning': 'Plain meaning',
  'shloka.idiomatic': 'Idiomatic translation',
  'shloka.literal': 'Literal translation',
  'shloka.showLiteral': 'Show literal',
  'shloka.showIdiomatic': 'Show idiomatic',
  'shloka.wordByWord': 'Word by word',
  'shloka.commentary': 'Commentary',
  'shloka.doctrinalContext': 'Doctrinal context',
  'shloka.practicalRelevance': 'Practical relevance',
  'shloka.crossReferences': 'Cross-references',
  'shloka.sources': 'Sources',
  'shloka.verse': 'Verse {n}',
  'shloka.copyVerse': 'Copy verse',
  'shloka.linkTitle': 'Copy a shareable link to this verse',
  'shloka.verseLinkTitle': 'Link to this verse',
  'shloka.confidence': 'translator confidence',

  // word-by-word table
  'wbw.word': 'Word',
  'wbw.iast': 'IAST',
  'wbw.meaning': 'Meaning',
  'wbw.type': 'Type',

  // source list
  'source.consultedFor': 'Consulted for:',

  // sutra page
  'sutra.about': 'About this sūtra',
  'sutra.howToRead': 'How to read this sūtra',
  'sutra.field.ritualPlacement': 'Ritual placement',
  'sutra.field.authorAndSource': 'Author & source',
  'sutra.field.structure': 'Structure',
  'sutra.field.imagery': 'Recurring imagery',
  'sutra.field.keyThemes': 'Key themes',
  'sutra.prefaceSources': 'Preface sources',
  'sutra.verses': 'Verses',
  'sutra.versesPresent': '{n} verses present',
  'sutra.gatha': '{n} gāthā',
  'sutra.book': 'Book · {pages}',
  'sutra.recitedIn': 'Recited in:',
  'sutra.sharedAcross': '↔ Shared across {n} rites',
  'sutra.smarana': 'Smaraṇa {n}',
  'sutra.printTitle': 'Print this sūtra',
  'sutra.prefacePending':
    'The introduction for this sūtra is not yet available in the selected language. Try another language above, or read the verses below.',
  'sutra.versePending':
    'The verse-by-verse text of this sūtra is pending from the source. It will appear here as the pipeline completes.',
  'sutra.notFound.title': 'Sūtra not found',

  // pratikraman page
  'prati.number': 'Pratikramaṇa #{order}',
  'prati.baseRite': 'Base rite',
  'prati.frequency': 'Frequency',
  'prati.covers': 'Covers',
  'prati.kausagga': 'Kāyotsarga',
  'prati.book': 'Book',
  'prati.sixAvashyakas': 'The six Āvaśyakas',
  'prati.sharedCore.label': 'Shared core. ',
  'prati.sharedCore.pre': 'This rite recites the core Āvaśyaka sūtras from ',
  'prati.sharedCore.post': ' (per its vidhi); the steps below are what the book prints for {name}.',
  'prati.counts': '{sutras} sūtras · {vidhis} instructions',
  'prati.derived.title': 'Performed exactly like {base}',
  'prati.derived.subtitle': 'The book defines {name} entirely by reference — it prints no separate text.',
  'prati.derived.wordSub': 'With this word-substitution',
  'prati.derived.kausagga': 'And this kāyotsarga',
  'prati.derived.openBase': 'Open the {base} sequence →',
  'prati.legend.derived':
    'Shown in full below — the complete order to recite. Steps highlighted are unique to {rite}; the rest is the shared Āvaśyaka core, recited as in {base}.',
  'prati.legend.reference':
    'Performed in full as {base}, with the change above. The complete order to recite is shown below.',
  'prov.specific': 'Specific to {rite}',
  'prov.shared': 'Shared core',
  'prov.inherited': 'As in {base}',
  'prati.notFound.title': 'Pratikramaṇa not found',
  'prati.notFound.detail': 'No rite with id “{id}”.',
  'vidhi.label': 'Instruction (vidhi)',
  'vidhi.goldenText': 'Source text · {pages}',
  'vidhi.show': 'Show recitation & meaning',
  'vidhi.hide': 'Hide recitation & meaning',
  'vidhi.adesh': 'Ādeśa',
  'vidhi.direction': 'Direction',
  'vidhi.formula': 'Formula',
  'vidhi.speaker.shishya': 'Disciple',
  'vidhi.speaker.guru': 'Guru',
  'vidhi.toRecite': 'To recite',
  'vidhi.leadsTo': 'Leads into',
  'vidhi.ritualTerms': 'Ritual terms',
  'vidhi.inProgress':
    'The native text & translation of this step are being prepared. Try another language, or check back as the corpus grows.',
  'step.shared': 'Shared',
  'step.sharedTitle': 'Shared across: {list}',
  'step.unknownSutra': 'Unknown sūtra: {id}',

  // home
  'home.hero.eyebrow': 'Jain Sacred Text · Śvetāmbara Mūrtipūjaka',
  'home.hero.title': 'The Five Pratikramaṇas',
  'home.hero.subtitle':
    'A reverent, three-language edition — English, ગુજરાતી, हिन्दी — with verse-by-verse commentary of the daily, fortnightly, seasonal and annual rites of reflection, confession, and renewal in the **Achhalgach (Vidhipakṣa)** tradition.',
  'home.hero.begin': 'Begin with Devasi',
  'home.hero.whatIs': 'What is Pratikramaṇa?',
  'home.stats.pratikramans': 'Pratikramaṇas',
  'home.stats.avashyakas': 'Āvaśyakas',
  'home.stats.sutras': 'Sūtras',
  'home.what.eyebrow': 'The meaning',
  'home.what.title': 'What is Pañca Pratikramaṇa?',
  'home.what.body':
    '*Pratikramaṇa* means **“turning back”** — the disciplined rite by which a practitioner returns from transgression to right conduct through reflection, confession (*ālocanā*), atonement, and renewal. *Pañca Pratikramaṇa* — the **five** pratikramaṇas — grade this self-review by the period of life it examines: a day, a night, a fortnight, a four-month season, and a whole year.',
  'home.doctrinal.title': 'Why it matters — doctrinally',
  'home.doctrinal.body':
    'Each rite is woven from the **six Āvaśyakas** (essential daily duties), turns on the **three jewels** — right faith, knowledge, and conduct — and is rooted in **ahiṁsā** and care for the entire four-fold Saṅgha of monks, nuns, laymen, and laywomen.',
  'home.practical.title': 'Why it matters — practically',
  'home.practical.body':
    'It is a structured rhythm of **self-review**: daily at dusk and dawn, fortnightly on the *chaudas*, at each season’s end, and once a year at *Saṁvatsarī* — restoring equanimity and resolve, again and again.',
  'home.avashyakaLegend': 'The six Āvaśyakas',
  'home.five.eyebrow': 'The corpus',
  'home.five.title': 'The Five Pratikramaṇas',
  'home.five.body':
    'Nested and shared: **Devasi** is the base; the others build upon it. Cāumāsī and Sāṁvatsarī reuse the Pākṣika with a word-substitution and a larger kāyotsarga.',
  'home.card.base': 'Base',
  'home.card.open': 'Open',
  'home.card.frequency': 'Frequency',
  'home.card.covers': 'Covers',
  'home.tradition.title': 'The tradition & the source book',
  'home.tradition.cta': 'Read about the Achhalgach lineage and method →',
  'home.howToRead.title': 'How to read this site',
  'home.howToRead.newcomer.title': 'For the newcomer',
  'home.howToRead.newcomer.body':
    'Start at the plain meaning and the “to recite” line of each verse. The five cards above lead you gently through each rite, with instructions shown in their own style.',
  'home.howToRead.practitioner.title': 'For the practitioner',
  'home.howToRead.practitioner.body':
    'Expand any verse for word-by-word parsing, etymology, commentary, doctrinal context, cross-references and cited sources. Toggle EN / ગુ / हि at any time; glossary terms define themselves on hover.',
  'home.source.note': 'Source of truth: {book}.',
  'home.source.fallback': 'the authoritative book of the tradition',

  // footer
  'footer.tagline':
    'A reverent, three-language edition with verse-by-verse commentary of the five Pratikramaṇa sūtras of the Achhalgach (Anchalgachchha / Vidhipakṣa) Śvetāmbara Mūrtipūjaka Jain tradition.',
  'footer.explore': 'Explore',
  'footer.link.intro': 'Introduction',
  'footer.link.five': 'The Five Pratikramaṇas',
  'footer.link.about': 'About & Method',
  'footer.link.design': 'Design System',
  'footer.provenance': 'Provenance',
  'footer.sourceFallback': 'Panch Pratikraman Sutra — Vidhi Sahit, Anchalgachchha (Vidhipaksha) edition.',
  'footer.downloadPdf': 'Download print PDF',
  'footer.bottom.pre':
    'The scripture is the hero; this site only serves it. Source of truth: the generated corpus. Translations and commentary are produced by an assisted pipeline and refined against classical lexica — see ',
  'footer.bottom.linkLabel': 'About',

  // glossary
  'glossary.eyebrow': 'Reference',
  'glossary.title': 'Glossary',
  'glossary.intro':
    'Key terms of doctrine, ritual, and imagery drawn from the sūtras. Hover any highlighted term across the site to see its definition; here you can browse and search the full set.',
  'glossary.searchPlaceholder': 'Search terms…',
  'glossary.searchAria': 'Search glossary',
  'glossary.count': '{n} terms',
  'glossary.countFiltered': '{n} of {total}',
  'glossary.terms': 'terms',
  'glossary.noMatch': 'No terms match “{q}”.',

  // about
  'about.hero.title': 'The Tradition & the Method',
  'about.hero.body':
    'This edition presents the Pañca Pratikramaṇa of the Achhalgach (Anchalgachchha / Vidhipakṣa) Śvetāmbara Mūrtipūjaka Jain tradition, with the tradition’s authoritative printed edition as its source.',
  'about.sourceBook.title': 'The source book',
  'about.corpus.title': 'Corpus at a glance',
  'about.corpus.sutras': 'Sūtras',
  'about.corpus.verses': 'Verses',
  'about.corpus.prefaces': 'Prefaces',
  'about.corpus.translations': 'Verse translations',
  'about.corpus.note':
    'The translation pipeline is ongoing; counts grow as new JSON is generated and the site is re-synced.',
  'about.method.title': 'Method',
  'about.method.body':
    'Verses follow the received text of the sūtras as found in the tradition’s authoritative printed edition. Translation and commentary are prepared from that source by an assisted pipeline and reconciled against classical Prakrit and Sanskrit lexica, with sources cited per verse.',
  'about.downloadPdf': 'Download print PDF',
  'about.loadingKb': 'Loading tradition knowledge…',
  'about.footer.made': 'Made with reverence. The scripture is the hero; this site only serves it.',
  'about.kbLangNote':
    'The tradition knowledge base below is currently available in English only.',

  // style / design system
  'style.eyebrow': 'Reviewable in isolation',
  'style.title': 'Design System',
  'style.intro':
    'The tokens, type scale, motifs, and core components that compose the site — a reverent visual language in service of the scripture.',
  'style.section.colors': 'Color tokens',
  'style.section.typography': 'Typography',
  'style.section.motifs': 'Motifs',
  'style.section.controls': 'Controls',
  'style.section.disclosure': 'Disclosure',
  'style.section.verse': 'Verse setting (sample)',
}

const gujarati: Dict = {
  'nav.home': 'મુખ્ય પૃષ્ઠ',
  'nav.rites': 'પ્રતિક્રમણ',
  'nav.glossary': 'શબ્દકોશ',
  'nav.about': 'પરિચય',
  'brand.subtitle': 'અંચલગચ્છ · વિધિપક્ષ',
  'search.button': 'શોધ',
  'search.aria': 'શોધ ખોલો',
  'toggle.lang': 'ભાષા પસંદ કરો',
  'toggle.theme.toLight': 'હળવી થીમ પર જાઓ',
  'toggle.theme.toDark': 'ઘેરી થીમ પર જાઓ',
  'toggle.menu': 'મેનૂ ખોલો/બંધ કરો',

  'search.placeholder': 'સૂત્રો, ગાથાઓ, શબ્દકોશ શોધો…',
  'search.hint': 'બધાં સૂત્રો, ગાથાઓ અને શબ્દકોશમાં શોધવા લખો.',
  'search.noMatch': '“{q}” માટે કોઈ પરિણામ નથી.',
  'search.type.sutra': 'સૂત્ર',
  'search.type.shloka': 'ગાથા',
  'search.type.glossary': 'શબ્દકોશ',
  'search.type.vidhi': 'વિધિ',

  'common.copy': 'નકલ કરો',
  'common.copied': 'નકલ થઈ',
  'common.copyTitle': 'ક્લિપબોર્ડમાં નકલ કરો',
  'common.save': 'સાચવો',
  'common.saved': 'સાચવ્યું',
  'common.print': 'છાપો',
  'common.loading': 'લોડ થઈ રહ્યું છે…',
  'common.preparing': 'સંગ્રહ તૈયાર થઈ રહ્યો છે…',
  'common.link': 'લિંક',

  'crumb.home': 'મુખ્ય પૃષ્ઠ',
  'crumb.sutras': 'સૂત્રો',
  'crumb.pratikramans': 'પ્રતિક્રમણ',
  'crumb.glossary': 'શબ્દકોશ',
  'crumb.about': 'પરિચય',
  'crumb.designSystem': 'ડિઝાઇન સિસ્ટમ',

  'error.title': 'કંઈક ખોટું થયું',
  'error.resync': 'જો અનુવાદ-પ્રક્રિયા હજી ચાલુ હોય, તો `npm run sync-data` ફરી ચલાવી પાનું રિફ્રેશ કરો.',
  'notFound.eyebrow': 'મળ્યું નહીં',
  'notFound.title': 'આ પાનું મળ્યું નહીં',
  'notFound.body':
    'લિંક ખોટી લખાઈ હોય, અથવા સંબંધિત લખાણ અનુવાદ-પ્રક્રિયા દ્વારા હજી ઉત્પન્ન થયું ન હોય.',
  'notFound.home': 'મુખ્ય પૃષ્ઠ પર પાછા',
  'notFound.browse': 'પ્રતિક્રમણ જુઓ',

  'progress.textPending': 'લખાણ બાકી',
  'progress.byLang': 'ભાષાવાર અનુવાદ-પ્રગતિ',
  'progress.verseTextPending': 'આ ભાગનો મૂળ ગાથા-પાઠ હજી કાઢવાનો બાકી છે.',
  'progress.verseInProgress':
    'આ ગાથાનો અનુવાદ અને વિવેચન પસંદ કરેલી ભાષામાં તૈયાર થઈ રહ્યું છે. બીજી ભાષા અજમાવો, અથવા સંગ્રહ વધે ત્યારે ફરી જુઓ.',

  'av.word': 'આવશ્યક',
  'av.short': 'આવ {n}',
  'av.ordinal.1': 'પહેલું',
  'av.ordinal.2': 'બીજું',
  'av.ordinal.3': 'ત્રીજું',
  'av.ordinal.4': 'ચોથું',
  'av.ordinal.5': 'પાંચમું',
  'av.ordinal.6': 'છઠ્ઠું',

  'shloka.toRecite': 'ઉચ્ચારણ માટે',
  'shloka.toReciteIast': 'ઉચ્ચારણ માટે (IAST)',
  'shloka.plainMeaning': 'સરળ અર્થ',
  'shloka.idiomatic': 'ભાવાનુવાદ',
  'shloka.literal': 'શબ્દશઃ અનુવાદ',
  'shloka.showLiteral': 'શબ્દશઃ બતાવો',
  'shloka.showIdiomatic': 'ભાવાનુવાદ બતાવો',
  'shloka.wordByWord': 'શબ્દ-વિશ્લેષણ',
  'shloka.commentary': 'વિવેચન',
  'shloka.doctrinalContext': 'સૈદ્ધાંતિક સંદર્ભ',
  'shloka.practicalRelevance': 'વ્યાવહારિક પ્રસ્તુતતા',
  'shloka.crossReferences': 'અન્ય સંદર્ભો',
  'shloka.sources': 'સ્રોત',
  'shloka.verse': 'ગાથા {n}',
  'shloka.copyVerse': 'ગાથા નકલ કરો',
  'shloka.linkTitle': 'આ ગાથાની લિંક નકલ કરો',
  'shloka.verseLinkTitle': 'આ ગાથાની લિંક',
  'shloka.confidence': 'અનુવાદક-વિશ્વાસ',

  'wbw.word': 'શબ્દ',
  'wbw.iast': 'IAST',
  'wbw.meaning': 'અર્થ',
  'wbw.type': 'પ્રકાર',

  'source.consultedFor': 'સંદર્ભ માટે:',

  'sutra.about': 'આ સૂત્ર વિશે',
  'sutra.howToRead': 'આ સૂત્ર કેવી રીતે વાંચવું',
  'sutra.field.ritualPlacement': 'વિધિ-સ્થાન',
  'sutra.field.authorAndSource': 'કર્તા અને સ્રોત',
  'sutra.field.structure': 'સંરચના',
  'sutra.field.imagery': 'પુનરાવર્તિત રૂપકો',
  'sutra.field.keyThemes': 'મુખ્ય વિષયો',
  'sutra.prefaceSources': 'પ્રસ્તાવના-સ્રોત',
  'sutra.verses': 'ગાથાઓ',
  'sutra.versesPresent': '{n} ગાથાઓ ઉપલબ્ધ',
  'sutra.gatha': '{n} ગાથા',
  'sutra.book': 'ગ્રંથ · {pages}',
  'sutra.recitedIn': 'અહીં પઠિત:',
  'sutra.sharedAcross': '↔ {n} વિધિઓમાં સહિયારું',
  'sutra.smarana': 'સ્મરણ {n}',
  'sutra.printTitle': 'આ સૂત્ર છાપો',
  'sutra.prefacePending':
    'આ સૂત્રની પ્રસ્તાવના પસંદ કરેલી ભાષામાં હજી ઉપલબ્ધ નથી. ઉપર બીજી ભાષા અજમાવો, અથવા નીચે ગાથાઓ વાંચો.',
  'sutra.versePending':
    'આ સૂત્રનો ગાથા-વાર પાઠ મૂળ ગ્રંથમાંથી કાઢવાનો બાકી છે. પ્રક્રિયા પૂર્ણ થતાં અહીં દેખાશે.',
  'sutra.notFound.title': 'સૂત્ર મળ્યું નહીં',

  'prati.number': 'પ્રતિક્રમણ #{order}',
  'prati.baseRite': 'મૂળ વિધિ',
  'prati.frequency': 'આવૃત્તિ',
  'prati.covers': 'વ્યાપ્તિ',
  'prati.kausagga': 'કાયોત્સર્ગ',
  'prati.book': 'ગ્રંથ',
  'prati.sixAvashyakas': 'છ આવશ્યક',
  'prati.sharedCore.label': 'સહિયારો મૂળ ભાગ. ',
  'prati.sharedCore.pre': 'આ વિધિ મૂળ આવશ્યક સૂત્રો ',
  'prati.sharedCore.post': ' માંથી (તેની વિધિ મુજબ) પઠે છે; નીચેનાં પગલાં ગ્રંથમાં {name} માટે છપાયેલાં છે.',
  'prati.counts': '{sutras} સૂત્રો · {vidhis} સૂચનાઓ',
  'prati.derived.title': '{base} ની જેમ જ કરાય છે',
  'prati.derived.subtitle': 'ગ્રંથ {name} ને સંપૂર્ણપણે સંદર્ભ દ્વારા વ્યાખ્યાયિત કરે છે — તેનો અલગ પાઠ છાપતો નથી.',
  'prati.derived.wordSub': 'આ શબ્દ-ફેરબદલ સાથે',
  'prati.derived.kausagga': 'અને આ કાયોત્સર્ગ',
  'prati.derived.openBase': '{base} ક્રમ ખોલો →',
  'prati.legend.derived':
    'નીચે સંપૂર્ણ ક્રમ — ઉચ્ચારવાનો સંપૂર્ણ ક્રમ. હાઇલાઇટ કરેલાં પગલાં {rite} માટે ખાસ છે; બાકીનાં {base} મુજબ પઠાતા સમાન આવશ્યક સૂત્રો છે.',
  'prati.legend.reference':
    'ઉપરના ફેરફાર સાથે, સંપૂર્ણપણે {base} મુજબ કરાય છે. ઉચ્ચારવાનો સંપૂર્ણ ક્રમ નીચે છે.',
  'prov.specific': '{rite} માટે વિશિષ્ટ',
  'prov.shared': 'સહિયારો કોર',
  'prov.inherited': '{base} મુજબ',
  'prati.notFound.title': 'પ્રતિક્રમણ મળ્યું નહીં',
  'prati.notFound.detail': '“{id}” આઈડી સાથે કોઈ વિધિ નથી.',
  'vidhi.label': 'સૂચના (વિધિ)',
  'vidhi.goldenText': 'મૂળ પાઠ · {pages}',
  'vidhi.show': 'ઉચ્ચારણ અને અર્થ બતાવો',
  'vidhi.hide': 'ઉચ્ચારણ અને અર્થ છુપાવો',
  'vidhi.adesh': 'આદેશ',
  'vidhi.direction': 'સૂચના',
  'vidhi.formula': 'સૂત્રપદ',
  'vidhi.speaker.shishya': 'શિષ્ય',
  'vidhi.speaker.guru': 'ગુરુ',
  'vidhi.toRecite': 'ઉચ્ચારણ માટે',
  'vidhi.leadsTo': 'આગળ દોરે છે',
  'vidhi.ritualTerms': 'વિધિ-પારિભાષિક શબ્દો',
  'vidhi.inProgress':
    'આ પગલાનો મૂળ પાઠ અને અનુવાદ તૈયાર થઈ રહ્યો છે. બીજી ભાષા અજમાવો, અથવા સંગ્રહ વધે ત્યારે ફરી જુઓ.',
  'step.shared': 'સહિયારું',
  'step.sharedTitle': 'અહીં સહિયારું: {list}',
  'step.unknownSutra': 'અજ્ઞાત સૂત્ર: {id}',

  'home.hero.eyebrow': 'જૈન પવિત્ર ગ્રંથ · શ્વેતામ્બર મૂર્તિપૂજક',
  'home.hero.title': 'પંચ પ્રતિક્રમણ',
  'home.hero.subtitle':
    'અંચલગચ્છ (**વિધિપક્ષ**) પરંપરાનાં દૈનિક, પાક્ષિક, ઋતુગત અને વાર્ષિક — ચિંતન, આલોચના અને નવીકરણનાં — વિધિવિધાનોનું, ગાથાવાર વિવેચન સહિત, ત્રિભાષી (અંગ્રેજી, ગુજરાતી, हिन्दी) શ્રદ્ધાપૂર્ણ સંસ્કરણ.',
  'home.hero.begin': 'દેવસિથી શરૂ કરો',
  'home.hero.whatIs': 'પ્રતિક્રમણ શું છે?',
  'home.stats.pratikramans': 'પ્રતિક્રમણ',
  'home.stats.avashyakas': 'આવશ્યક',
  'home.stats.sutras': 'સૂત્રો',
  'home.what.eyebrow': 'અર્થ',
  'home.what.title': 'પંચ પ્રતિક્રમણ શું છે?',
  'home.what.body':
    '*પ્રતિક્રમણ* એટલે **“પાછા ફરવું”** — એ સંયમિત વિધિ જેના વડે સાધક અતિચારથી પાછા ફરી, ચિંતન, આલોચના, પ્રાયશ્ચિત્ત અને નવીકરણ દ્વારા સમ્યક્ આચાર તરફ વળે છે. *પંચ પ્રતિક્રમણ* — **પાંચ** પ્રતિક્રમણ — આ આત્મ-નિરીક્ષણને જે કાળખંડ તપાસે તે પ્રમાણે વર્ગીકૃત કરે છે: એક દિવસ, એક રાત્રિ, એક પક્ષ, ચાતુર્માસ અને સમગ્ર વર્ષ.',
  'home.doctrinal.title': 'શા માટે મહત્ત્વનું — સૈદ્ધાંતિક રીતે',
  'home.doctrinal.body':
    'પ્રત્યેક વિધિ **છ આવશ્યક** (દૈનિક અનિવાર્ય કર્તવ્યો) થી રચાય છે, **રત્નત્રય** — સમ્યગ્ દર્શન, જ્ઞાન અને ચારિત્ર — પર આધારિત છે, અને **અહિંસા** તથા સાધુ-સાધ્વી-શ્રાવક-શ્રાવિકારૂપ ચતુર્વિધ સંઘ પ્રત્યેની કાળજીમાં મૂળ ધરાવે છે.',
  'home.practical.title': 'શા માટે મહત્ત્વનું — વ્યાવહારિક રીતે',
  'home.practical.body':
    'આ **આત્મ-નિરીક્ષણ**ની સુવ્યવસ્થિત લય છે: પ્રતિદિન સંધ્યા અને પ્રભાતે, પક્ષે *ચૌદશ*ના દિને, પ્રત્યેક ઋતુને અંતે, અને વર્ષમાં એક વાર *સંવત્સરી*એ — વારંવાર સમતા અને સંકલ્પને પુનઃસ્થાપિત કરતી.',
  'home.avashyakaLegend': 'છ આવશ્યક',
  'home.five.eyebrow': 'સંગ્રહ',
  'home.five.title': 'પંચ પ્રતિક્રમણ',
  'home.five.body':
    'પરસ્પર સંકળાયેલાં અને સહિયારાં: **દેવસિ** મૂળ છે; બાકીનાં તેના પર રચાય છે. ચાતુર્માસિક અને સાંવત્સરિક પાક્ષિકને જ શબ્દ-ફેરબદલ અને મોટા કાયોત્સર્ગ સાથે પુનઃ ઉપયોગ કરે છે.',
  'home.card.base': 'મૂળ',
  'home.card.open': 'ખોલો',
  'home.card.frequency': 'આવૃત્તિ',
  'home.card.covers': 'વ્યાપ્તિ',
  'home.tradition.title': 'પરંપરા અને મૂળ ગ્રંથ',
  'home.tradition.cta': 'અંચલગચ્છ પરંપરા અને પદ્ધતિ વિશે વાંચો →',
  'home.howToRead.title': 'આ સ્થળ કેવી રીતે વાંચવું',
  'home.howToRead.newcomer.title': 'નવા વાચક માટે',
  'home.howToRead.newcomer.body':
    'પ્રત્યેક ગાથાના સરળ અર્થ અને “ઉચ્ચારણ માટે” પંક્તિથી શરૂ કરો. ઉપરનાં પાંચ કાર્ડ તમને પ્રત્યેક વિધિમાંથી સહજ રીતે દોરી જાય છે, જ્યાં સૂચનાઓ પોતાની અલગ શૈલીમાં દર્શાવેલી છે.',
  'home.howToRead.practitioner.title': 'સાધક માટે',
  'home.howToRead.practitioner.body':
    'કોઈ પણ ગાથાને વિસ્તારી શબ્દશઃ વિશ્લેષણ, વ્યુત્પત્તિ, વિવેચન, સૈદ્ધાંતિક સંદર્ભ, અન્ય સંદર્ભો અને ઉલ્લેખિત સ્રોત જુઓ. ગમે ત્યારે EN / ગુ / हि બદલો; શબ્દકોશના શબ્દો સ્પર્શ કરતાં અર્થ બતાવે છે.',
  'home.source.note': 'પ્રમાણ-સ્રોત: {book}.',
  'home.source.fallback': 'પરંપરાનો પ્રમાણભૂત ગ્રંથ',

  'footer.tagline':
    'અંચલગચ્છ (વિધિપક્ષ) શ્વેતામ્બર મૂર્તિપૂજક જૈન પરંપરાનાં પંચ પ્રતિક્રમણ સૂત્રોનું, ગાથાવાર વિવેચન સહિત, ત્રિભાષી શ્રદ્ધાપૂર્ણ સંસ્કરણ.',
  'footer.explore': 'અન્વેષણ',
  'footer.link.intro': 'પ્રસ્તાવના',
  'footer.link.five': 'પંચ પ્રતિક્રમણ',
  'footer.link.about': 'પરિચય અને પદ્ધતિ',
  'footer.link.design': 'ડિઝાઇન સિસ્ટમ',
  'footer.provenance': 'ઉદ્ગમ',
  'footer.sourceFallback': 'પંચ પ્રતિક્રમણ સૂત્ર – વિધિ સહિત, અંચલગચ્છ (વિધિપક્ષ) સંસ્કરણ.',
  'footer.downloadPdf': 'છાપ-PDF ડાઉનલોડ કરો',
  'footer.bottom.pre':
    'ગ્રંથ જ નાયક છે; આ સ્થળ માત્ર તેની સેવા કરે છે. પ્રમાણ-સ્રોત: ઉત્પન્ન સંગ્રહ. અનુવાદ અને વિવેચન સહાયિત પ્રક્રિયા દ્વારા તૈયાર થાય છે અને શાસ્ત્રીય કોશો સામે પરિષ્કૃત — જુઓ ',
  'footer.bottom.linkLabel': 'પરિચય',

  'glossary.eyebrow': 'સંદર્ભ',
  'glossary.title': 'શબ્દકોશ',
  'glossary.intro':
    'સૂત્રોમાંથી લીધેલા સિદ્ધાંત, વિધિ અને રૂપકના મુખ્ય શબ્દો. સ્થળભરમાં કોઈ પણ ચિહ્નિત શબ્દ પર સ્પર્શ કરી તેનો અર્થ જુઓ; અહીં તમે સમગ્ર સંગ્રહ જોઈ અને શોધી શકો છો.',
  'glossary.searchPlaceholder': 'શબ્દ શોધો…',
  'glossary.searchAria': 'શબ્દકોશ શોધો',
  'glossary.count': '{n} શબ્દો',
  'glossary.countFiltered': '{total} માંથી {n}',
  'glossary.terms': 'શબ્દો',
  'glossary.noMatch': '“{q}” સાથે મેળ ખાતો કોઈ શબ્દ નથી.',

  'about.hero.title': 'પરંપરા અને પદ્ધતિ',
  'about.hero.body':
    'આ સંસ્કરણ અંચલગચ્છ (વિધિપક્ષ) શ્વેતામ્બર મૂર્તિપૂજક જૈન પરંપરાનું પંચ પ્રતિક્રમણ રજૂ કરે છે, જે પરંપરાના પ્રમાણભૂત મુદ્રિત ગ્રંથને સ્રોત તરીકે આધાર બનાવે છે.',
  'about.sourceBook.title': 'મૂળ ગ્રંથ',
  'about.corpus.title': 'સંગ્રહ એક નજરમાં',
  'about.corpus.sutras': 'સૂત્રો',
  'about.corpus.verses': 'ગાથાઓ',
  'about.corpus.prefaces': 'પ્રસ્તાવનાઓ',
  'about.corpus.translations': 'ગાથા-અનુવાદ',
  'about.corpus.note':
    'અનુવાદ-પ્રક્રિયા ચાલુ છે; નવી JSON ઉત્પન્ન થતાં અને સ્થળ ફરી સિંક થતાં સંખ્યા વધે છે.',
  'about.method.title': 'પદ્ધતિ',
  'about.method.body':
    'ગાથાઓ પરંપરાના પ્રમાણભૂત મુદ્રિત ગ્રંથમાં મળતા પ્રચલિત પાઠ પ્રમાણે છે. અનુવાદ અને વિવેચન સહાયિત પ્રક્રિયા દ્વારા તૈયાર થાય છે અને શાસ્ત્રીય પ્રાકૃત તથા સંસ્કૃત કોશો સામે મેળવાય છે, પ્રત્યેક ગાથા સાથે સ્રોત ઉલ્લેખિત.',
  'about.downloadPdf': 'છાપ-PDF ડાઉનલોડ કરો',
  'about.loadingKb': 'પરંપરા-જ્ઞાન લોડ થઈ રહ્યું છે…',
  'about.footer.made': 'શ્રદ્ધાપૂર્વક રચિત. ગ્રંથ જ નાયક છે; આ સ્થળ માત્ર તેની સેવા કરે છે.',
  'about.kbLangNote': 'નીચેનો પરંપરા-જ્ઞાનકોશ હાલમાં માત્ર અંગ્રેજીમાં ઉપલબ્ધ છે.',

  'style.eyebrow': 'સ્વતંત્ર રીતે સમીક્ષાયોગ્ય',
  'style.title': 'ડિઝાઇન સિસ્ટમ',
  'style.intro':
    'સ્થળને રચતા ટોકન, ટાઇપ-સ્કેલ, રૂપકો અને મુખ્ય ઘટકો — ગ્રંથની સેવામાં શ્રદ્ધાપૂર્ણ દૃશ્ય-ભાષા.',
  'style.section.colors': 'રંગ-ટોકન',
  'style.section.typography': 'ટાઇપોગ્રાફી',
  'style.section.motifs': 'રૂપકો',
  'style.section.controls': 'નિયંત્રણો',
  'style.section.disclosure': 'વિસ્તરણ',
  'style.section.verse': 'ગાથા-ગોઠવણી (નમૂનો)',
}

const hindi: Dict = {
  'nav.home': 'मुख्य पृष्ठ',
  'nav.rites': 'प्रतिक्रमण',
  'nav.glossary': 'शब्दकोश',
  'nav.about': 'परिचय',
  'brand.subtitle': 'अंचलगच्छ · विधिपक्ष',
  'search.button': 'खोज',
  'search.aria': 'खोज खोलें',
  'toggle.lang': 'भाषा चुनें',
  'toggle.theme.toLight': 'हल्की थीम पर जाएँ',
  'toggle.theme.toDark': 'गहरी थीम पर जाएँ',
  'toggle.menu': 'मेनू खोलें/बंद करें',

  'search.placeholder': 'सूत्र, गाथाएँ, शब्दकोश खोजें…',
  'search.hint': 'सभी सूत्रों, गाथाओं और शब्दकोश में खोजने के लिए लिखें।',
  'search.noMatch': '“{q}” के लिए कोई परिणाम नहीं।',
  'search.type.sutra': 'सूत्र',
  'search.type.shloka': 'गाथा',
  'search.type.glossary': 'शब्दकोश',
  'search.type.vidhi': 'विधि',

  'common.copy': 'कॉपी करें',
  'common.copied': 'कॉपी हो गया',
  'common.copyTitle': 'क्लिपबोर्ड में कॉपी करें',
  'common.save': 'सहेजें',
  'common.saved': 'सहेजा गया',
  'common.print': 'प्रिंट करें',
  'common.loading': 'लोड हो रहा है…',
  'common.preparing': 'संग्रह तैयार हो रहा है…',
  'common.link': 'लिंक',

  'crumb.home': 'मुख्य पृष्ठ',
  'crumb.sutras': 'सूत्र',
  'crumb.pratikramans': 'प्रतिक्रमण',
  'crumb.glossary': 'शब्दकोश',
  'crumb.about': 'परिचय',
  'crumb.designSystem': 'डिज़ाइन सिस्टम',

  'error.title': 'कुछ गलत हो गया',
  'error.resync': 'यदि अनुवाद-प्रक्रिया अभी चल रही है, तो `npm run sync-data` फिर से चलाएँ और पेज रीलोड करें।',
  'notFound.eyebrow': 'नहीं मिला',
  'notFound.title': 'यह पेज नहीं मिला',
  'notFound.body':
    'लिंक गलत लिखा हो सकता है, या संबंधित पाठ अनुवाद-प्रक्रिया द्वारा अभी उत्पन्न नहीं हुआ है।',
  'notFound.home': 'मुख्य पृष्ठ पर लौटें',
  'notFound.browse': 'प्रतिक्रमण देखें',

  'progress.textPending': 'पाठ शेष',
  'progress.byLang': 'भाषावार अनुवाद-प्रगति',
  'progress.verseTextPending': 'इस अंश का मूल गाथा-पाठ अभी निकाला जाना शेष है।',
  'progress.verseInProgress':
    'इस गाथा का अनुवाद और विवेचन चयनित भाषा में तैयार हो रहा है। दूसरी भाषा आज़माएँ, या संग्रह बढ़ने पर फिर देखें।',

  'av.word': 'आवश्यक',
  'av.short': 'आव {n}',
  'av.ordinal.1': 'पहला',
  'av.ordinal.2': 'दूसरा',
  'av.ordinal.3': 'तीसरा',
  'av.ordinal.4': 'चौथा',
  'av.ordinal.5': 'पाँचवाँ',
  'av.ordinal.6': 'छठा',

  'shloka.toRecite': 'उच्चारण हेतु',
  'shloka.toReciteIast': 'उच्चारण हेतु (IAST)',
  'shloka.plainMeaning': 'सरल अर्थ',
  'shloka.idiomatic': 'भावानुवाद',
  'shloka.literal': 'शब्दशः अनुवाद',
  'shloka.showLiteral': 'शब्दशः दिखाएँ',
  'shloka.showIdiomatic': 'भावानुवाद दिखाएँ',
  'shloka.wordByWord': 'शब्द-विश्लेषण',
  'shloka.commentary': 'विवेचन',
  'shloka.doctrinalContext': 'सैद्धांतिक संदर्भ',
  'shloka.practicalRelevance': 'व्यावहारिक प्रासंगिकता',
  'shloka.crossReferences': 'अन्य संदर्भ',
  'shloka.sources': 'स्रोत',
  'shloka.verse': 'गाथा {n}',
  'shloka.copyVerse': 'गाथा कॉपी करें',
  'shloka.linkTitle': 'इस गाथा का साझा-लिंक कॉपी करें',
  'shloka.verseLinkTitle': 'इस गाथा का लिंक',
  'shloka.confidence': 'अनुवादक-विश्वास',

  'wbw.word': 'शब्द',
  'wbw.iast': 'IAST',
  'wbw.meaning': 'अर्थ',
  'wbw.type': 'प्रकार',

  'source.consultedFor': 'संदर्भ हेतु:',

  'sutra.about': 'इस सूत्र के बारे में',
  'sutra.howToRead': 'इस सूत्र को कैसे पढ़ें',
  'sutra.field.ritualPlacement': 'विधि-स्थान',
  'sutra.field.authorAndSource': 'रचयिता और स्रोत',
  'sutra.field.structure': 'संरचना',
  'sutra.field.imagery': 'आवर्ती रूपक',
  'sutra.field.keyThemes': 'मुख्य विषय',
  'sutra.prefaceSources': 'प्रस्तावना-स्रोत',
  'sutra.verses': 'गाथाएँ',
  'sutra.versesPresent': '{n} गाथाएँ उपलब्ध',
  'sutra.gatha': '{n} गाथा',
  'sutra.book': 'ग्रंथ · {pages}',
  'sutra.recitedIn': 'यहाँ पठित:',
  'sutra.sharedAcross': '↔ {n} विधियों में साझा',
  'sutra.smarana': 'स्मरण {n}',
  'sutra.printTitle': 'इस सूत्र को प्रिंट करें',
  'sutra.prefacePending':
    'इस सूत्र की प्रस्तावना चयनित भाषा में अभी उपलब्ध नहीं है। ऊपर दूसरी भाषा आज़माएँ, या नीचे गाथाएँ पढ़ें।',
  'sutra.versePending':
    'इस सूत्र का गाथावार पाठ मूल ग्रंथ से निकाला जाना शेष है। प्रक्रिया पूर्ण होने पर यहाँ दिखाई देगा।',
  'sutra.notFound.title': 'सूत्र नहीं मिला',

  'prati.number': 'प्रतिक्रमण #{order}',
  'prati.baseRite': 'मूल विधि',
  'prati.frequency': 'आवृत्ति',
  'prati.covers': 'व्याप्ति',
  'prati.kausagga': 'कायोत्सर्ग',
  'prati.book': 'ग्रंथ',
  'prati.sixAvashyakas': 'छह आवश्यक',
  'prati.sharedCore.label': 'साझा मूल भाग। ',
  'prati.sharedCore.pre': 'यह विधि मूल आवश्यक सूत्र ',
  'prati.sharedCore.post': ' से (उसकी विधि अनुसार) पढ़ती है; नीचे दिए चरण ग्रंथ में {name} हेतु छपे हैं।',
  'prati.counts': '{sutras} सूत्र · {vidhis} निर्देश',
  'prati.derived.title': '{base} की तरह ही किया जाता है',
  'prati.derived.subtitle': 'ग्रंथ {name} को पूर्णतः संदर्भ द्वारा परिभाषित करता है — इसका अलग पाठ नहीं छापता।',
  'prati.derived.wordSub': 'इस शब्द-प्रतिस्थापन के साथ',
  'prati.derived.kausagga': 'और यह कायोत्सर्ग',
  'prati.derived.openBase': '{base} क्रम खोलें →',
  'prati.legend.derived':
    'नीचे संपूर्ण क्रम — उच्चारण का पूरा क्रम। उजागर किए चरण {rite} के लिए विशिष्ट हैं; शेष {base} के अनुसार पढ़ा जाने वाला साझा आवश्यक मूल है।',
  'prati.legend.reference':
    'उपर दिए परिवर्तन के साथ, पूर्णतः {base} के अनुसार किया जाता है। संपूर्ण क्रम नीचे दिया है।',
  'prov.specific': '{rite} हेतु विशिष्ट',
  'prov.shared': 'साझा मूल',
  'prov.inherited': '{base} के अनुसार',
  'prati.notFound.title': 'प्रतिक्रमण नहीं मिला',
  'prati.notFound.detail': '“{id}” आईडी वाली कोई विधि नहीं।',
  'vidhi.label': 'निर्देश (विधि)',
  'vidhi.goldenText': 'मूल पाठ · {pages}',
  'vidhi.show': 'उच्चारण और अर्थ दिखाएँ',
  'vidhi.hide': 'उच्चारण और अर्थ छिपाएँ',
  'vidhi.adesh': 'आदेश',
  'vidhi.direction': 'निर्देश',
  'vidhi.formula': 'सूत्रपद',
  'vidhi.speaker.shishya': 'शिष्य',
  'vidhi.speaker.guru': 'गुरु',
  'vidhi.toRecite': 'उच्चारण हेतु',
  'vidhi.leadsTo': 'आगे ले जाता है',
  'vidhi.ritualTerms': 'विधि-पारिभाषिक शब्द',
  'vidhi.inProgress':
    'इस चरण का मूल पाठ और अनुवाद तैयार हो रहा है। दूसरी भाषा आज़माएँ, या संग्रह बढ़ने पर फिर देखें।',
  'step.shared': 'साझा',
  'step.sharedTitle': 'यहाँ साझा: {list}',
  'step.unknownSutra': 'अज्ञात सूत्र: {id}',

  'home.hero.eyebrow': 'जैन पवित्र ग्रंथ · श्वेतांबर मूर्तिपूजक',
  'home.hero.title': 'पंच प्रतिक्रमण',
  'home.hero.subtitle':
    'अंचलगच्छ (**विधिपक्ष**) परंपरा के दैनिक, पाक्षिक, ऋतुगत और वार्षिक — चिंतन, आलोचना और नवीनीकरण के — विधि-विधानों का, गाथावार विवेचन सहित, त्रिभाषी (अंग्रेज़ी, ગુજરાતી, हिन्दी) श्रद्धापूर्ण संस्करण।',
  'home.hero.begin': 'देवसि से आरंभ करें',
  'home.hero.whatIs': 'प्रतिक्रमण क्या है?',
  'home.stats.pratikramans': 'प्रतिक्रमण',
  'home.stats.avashyakas': 'आवश्यक',
  'home.stats.sutras': 'सूत्र',
  'home.what.eyebrow': 'अर्थ',
  'home.what.title': 'पंच प्रतिक्रमण क्या है?',
  'home.what.body':
    '*प्रतिक्रमण* का अर्थ है **“पीछे लौटना”** — वह संयमित विधि जिसके द्वारा साधक अतिचार से लौटकर, चिंतन, आलोचना, प्रायश्चित्त और नवीनीकरण के द्वारा सम्यक् आचार की ओर लौटता है। *पंच प्रतिक्रमण* — **पाँच** प्रतिक्रमण — इस आत्म-निरीक्षण को जिस कालखंड की वह समीक्षा करता है उसके अनुसार वर्गीकृत करते हैं: एक दिन, एक रात्रि, एक पक्ष, चातुर्मास और सम्पूर्ण वर्ष।',
  'home.doctrinal.title': 'क्यों महत्त्वपूर्ण — सैद्धांतिक रूप से',
  'home.doctrinal.body':
    'प्रत्येक विधि **छह आवश्यक** (दैनिक अनिवार्य कर्तव्यों) से रची जाती है, **रत्नत्रय** — सम्यग् दर्शन, ज्ञान और चारित्र — पर आधारित है, और **अहिंसा** तथा साधु-साध्वी-श्रावक-श्राविका रूप चतुर्विध संघ के प्रति देखभाल में निहित है।',
  'home.practical.title': 'क्यों महत्त्वपूर्ण — व्यावहारिक रूप से',
  'home.practical.body':
    'यह **आत्म-निरीक्षण** की सुव्यवस्थित लय है: प्रतिदिन संध्या और प्रभात में, पक्ष में *चौदस* को, प्रत्येक ऋतु के अंत में, और वर्ष में एक बार *संवत्सरी* को — बार-बार समता और संकल्प को पुनः स्थापित करती हुई।',
  'home.avashyakaLegend': 'छह आवश्यक',
  'home.five.eyebrow': 'संग्रह',
  'home.five.title': 'पंच प्रतिक्रमण',
  'home.five.body':
    'परस्पर जुड़े और साझा: **देवसि** आधार है; शेष उसी पर रचे जाते हैं। चातुर्मासिक और सांवत्सरिक पाक्षिक को ही शब्द-प्रतिस्थापन और बड़े कायोत्सर्ग के साथ पुनः उपयोग करते हैं।',
  'home.card.base': 'मूल',
  'home.card.open': 'खोलें',
  'home.card.frequency': 'आवृत्ति',
  'home.card.covers': 'व्याप्ति',
  'home.tradition.title': 'परंपरा और मूल ग्रंथ',
  'home.tradition.cta': 'अंचलगच्छ परंपरा और पद्धति के बारे में पढ़ें →',
  'home.howToRead.title': 'इस साइट को कैसे पढ़ें',
  'home.howToRead.newcomer.title': 'नए पाठक के लिए',
  'home.howToRead.newcomer.body':
    'प्रत्येक गाथा के सरल अर्थ और “उच्चारण हेतु” पंक्ति से आरंभ करें। ऊपर दिए पाँच कार्ड आपको प्रत्येक विधि से सहजता से ले जाते हैं, जहाँ निर्देश अपनी अलग शैली में दिखाए गए हैं।',
  'home.howToRead.practitioner.title': 'साधक के लिए',
  'home.howToRead.practitioner.body':
    'किसी भी गाथा को विस्तृत कर शब्दशः विश्लेषण, व्युत्पत्ति, विवेचन, सैद्धांतिक संदर्भ, अन्य संदर्भ और उद्धृत स्रोत देखें। कभी भी EN / ગુ / हि बदलें; शब्दकोश के शब्द छूने पर अर्थ बताते हैं।',
  'home.source.note': 'प्रामाणिक स्रोत: {book}।',
  'home.source.fallback': 'परंपरा का प्रामाणिक ग्रंथ',

  'footer.tagline':
    'अंचलगच्छ (विधिपक्ष) श्वेतांबर मूर्तिपूजक जैन परंपरा के पंच प्रतिक्रमण सूत्रों का, गाथावार विवेचन सहित, त्रिभाषी श्रद्धापूर्ण संस्करण।',
  'footer.explore': 'अन्वेषण',
  'footer.link.intro': 'प्रस्तावना',
  'footer.link.five': 'पंच प्रतिक्रमण',
  'footer.link.about': 'परिचय और पद्धति',
  'footer.link.design': 'डिज़ाइन सिस्टम',
  'footer.provenance': 'उद्गम',
  'footer.sourceFallback': 'पंच प्रतिक्रमण सूत्र – विधि सहित, अंचलगच्छ (विधिपक्ष) संस्करण।',
  'footer.downloadPdf': 'प्रिंट PDF डाउनलोड करें',
  'footer.bottom.pre':
    'ग्रंथ ही नायक है; यह साइट केवल उसकी सेवा करती है। प्रामाणिक स्रोत: उत्पन्न संग्रह। अनुवाद और विवेचन सहायित प्रक्रिया द्वारा तैयार होते हैं और शास्त्रीय कोशों के विरुद्ध परिष्कृत — देखें ',
  'footer.bottom.linkLabel': 'परिचय',

  'glossary.eyebrow': 'संदर्भ',
  'glossary.title': 'शब्दकोश',
  'glossary.intro':
    'सूत्रों से लिए गए सिद्धांत, विधि और रूपक के मुख्य शब्द। साइट भर में किसी भी चिह्नित शब्द पर माउस ले जाकर उसका अर्थ देखें; यहाँ आप संपूर्ण संग्रह देख और खोज सकते हैं।',
  'glossary.searchPlaceholder': 'शब्द खोजें…',
  'glossary.searchAria': 'शब्दकोश खोजें',
  'glossary.count': '{n} शब्द',
  'glossary.countFiltered': '{total} में से {n}',
  'glossary.terms': 'शब्द',
  'glossary.noMatch': '“{q}” से मेल खाता कोई शब्द नहीं।',

  'about.hero.title': 'परंपरा और पद्धति',
  'about.hero.body':
    'यह संस्करण अंचलगच्छ (विधिपक्ष) श्वेतांबर मूर्तिपूजक जैन परंपरा का पंच प्रतिक्रमण प्रस्तुत करता है, जो उसके प्रामाणिक मुद्रित ग्रंथ को स्रोत मानकर आधारित है।',
  'about.sourceBook.title': 'मूल ग्रंथ',
  'about.corpus.title': 'संग्रह एक नज़र में',
  'about.corpus.sutras': 'सूत्र',
  'about.corpus.verses': 'गाथाएँ',
  'about.corpus.prefaces': 'प्रस्तावनाएँ',
  'about.corpus.translations': 'गाथा-अनुवाद',
  'about.corpus.note':
    'अनुवाद-प्रक्रिया जारी है; नई JSON बनने और साइट के पुनः सिंक होने पर संख्याएँ बढ़ती हैं।',
  'about.method.title': 'पद्धति',
  'about.method.body':
    'गाथाएँ परंपरा के प्रामाणिक मुद्रित ग्रंथ में प्राप्त प्रचलित पाठ के अनुसार हैं। अनुवाद और विवेचन सहायित प्रक्रिया द्वारा तैयार होते हैं और शास्त्रीय प्राकृत तथा संस्कृत कोशों से मिलाए जाते हैं, प्रत्येक गाथा के साथ स्रोत उद्धृत।',
  'about.downloadPdf': 'प्रिंट PDF डाउनलोड करें',
  'about.loadingKb': 'परंपरा-ज्ञान लोड हो रहा है…',
  'about.footer.made': 'श्रद्धापूर्वक रचित। ग्रंथ ही नायक है; यह साइट केवल उसकी सेवा करती है।',
  'about.kbLangNote': 'नीचे दिया परंपरा-ज्ञानकोश फिलहाल केवल अंग्रेज़ी में उपलब्ध है।',

  'style.eyebrow': 'स्वतंत्र रूप से समीक्षा-योग्य',
  'style.title': 'डिज़ाइन सिस्टम',
  'style.intro':
    'साइट को रचने वाले टोकन, टाइप-स्केल, रूपक और मुख्य घटक — ग्रंथ की सेवा में श्रद्धापूर्ण दृश्य-भाषा।',
  'style.section.colors': 'रंग-टोकन',
  'style.section.typography': 'टाइपोग्राफी',
  'style.section.motifs': 'रूपक',
  'style.section.controls': 'नियंत्रण',
  'style.section.disclosure': 'विस्तरण',
  'style.section.verse': 'गाथा-संयोजन (नमूना)',
}

const STRINGS: Record<Lang, Dict> = { english, gujarati, hindi }

export function translate(lang: Lang, key: string, vars?: Record<string, string | number>): string {
  let s = STRINGS[lang]?.[key] ?? STRINGS.english[key] ?? key
  if (vars) {
    for (const [k, v] of Object.entries(vars)) {
      s = s.replace(new RegExp(`\\{${k}\\}`, 'g'), String(v))
    }
  }
  return s
}
