#!/usr/bin/env node
// Assemble the per-page OCR files into ONE golden, page-marked, human-readable
// markdown document, and mark the OCR manifest pages as verified.
//
// Inputs : data/book/pages/page-NNN.txt  (+ .meta.json)
// Outputs: data/book/panch-pratikraman.full.md
//          data/book/ocr-manifest.json   (statuses -> verified, bookPage filled)
//
// Re-run any time the per-page files change:  node scripts/assemble-book.mjs

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { loadConfig } from "../src/config.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const config = loadConfig(path.join(ROOT, "config.txt"));

const pagesDir = path.join(config.dataDir, "book", "pages");
const bookDir = path.join(config.dataDir, "book");
const pad = (n) => String(n).padStart(3, "0");

// --- gather pages ---
const txtFiles = fs.readdirSync(pagesDir).filter(f => /^page-\d{3}\.txt$/.test(f)).sort();
if (txtFiles.length === 0) { console.error("No page-NNN.txt files found."); process.exit(1); }

function parsePage(txt) {
    const lines = txt.split(/\r?\n/);
    let bookPage = "?", header = "-";
    let i = 0;
    for (; i < lines.length; i++) {
        const l = lines[i];
        if (l.startsWith("# book_page:")) bookPage = l.slice(12).trim();
        else if (l.startsWith("# header:")) header = l.slice(9).trim();
        else if (l.startsWith("# page:")) { /* skip */ }
        else if (l.trim() === "" && i > 0) { i++; break; }
    }
    const rest = lines.slice(i);
    const fi = rest.findIndex(l => l.trim() === "--- FOOTNOTES ---");
    const body = (fi >= 0 ? rest.slice(0, fi) : rest).join("\n").trim();
    const footnotes = fi >= 0 ? rest.slice(fi + 1).join("\n").trim() : "";
    return { bookPage, header, body, footnotes };
}

const out = [];
out.push("# પંચ પ્રતિક્રમણ સૂત્ર – વિધિ સહિત");
out.push("");
out.push("> **Panch Pratikraman Sutra — Vidhi Sahit** · Anchalgachchha (Vidhipaksha / Achhalgach) Śvetāmbara tradition.");
  out.push("> Source text, assembled from the printed edition of the book. **This is the single authoritative source** for all sutras and vidhi.");
out.push("> Generated by `scripts/assemble-book.mjs`. Do not hand-edit — edit `data/book/pages/page-NNN.txt` and re-run.");
out.push("");

const manifestPath = path.join(bookDir, "ocr-manifest.json");
const manifest = JSON.parse(fs.readFileSync(manifestPath, "utf8"));
const bookPageByPage = {};

for (const f of txtFiles) {
    const n = parseInt(f.match(/\d{3}/)[0], 10);
    const { bookPage, header, body, footnotes } = parsePage(fs.readFileSync(path.join(pagesDir, f), "utf8"));
    bookPageByPage[n] = bookPage;
    out.push("---");
    out.push("");
    out.push(`## Page ${pad(n)} — book p.${bookPage}`);
    out.push("");
    if (header && header !== "-") { out.push(`*${header}*`); out.push(""); }
    out.push(body);
    out.push("");
    if (footnotes) {
        out.push("> **Footnotes (page bottom):**");
        for (const fl of footnotes.split(/\r?\n/)) out.push(`> ${fl}`);
        out.push("");
    }
}

const fullPath = path.join(bookDir, "panch-pratikraman.full.md");
fs.writeFileSync(fullPath, out.join("\n") + "\n", "utf8");

// --- update manifest ---
let verified = 0;
for (const p of manifest.pages) {
    if (fs.existsSync(path.join(pagesDir, `page-${pad(p.page)}.txt`))) {
        p.status = "verified";
        if (bookPageByPage[p.page]) p.bookPage = bookPageByPage[p.page];
        verified++;
    }
}
manifest.verified = verified;
manifest.verifiedAt = new Date().toISOString();
fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2) + "\n", "utf8");

const chars = out.join("\n").length;
console.log(`Assembled ${txtFiles.length} pages -> ${path.relative(ROOT, fullPath)} (${(chars / 1024).toFixed(0)} KB)`);
console.log(`Manifest: ${verified}/${manifest.pageCount} pages marked verified.`);
